spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#spring.datasource.url=jdbc:mysql://localhost:3306/backendmr?useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=

#Ambiente de produccion
spring.datasource.url=jdbc:mysql://usvt440af7n8mjj8:gcu50QCwwiX4Wh3sSCzM@bp60dg40nh0b4exvzom0-mysql.services.clever-cloud.com:3306/bp60dg40nh0b4exvzom0
spring.datasource.username=usvt440af7n8mjj8
spring.datasource.password=gcu50QCwwiX4Wh3sSCzM

#JWT
jwt.secret = secret
jwt.expiration = 3600